version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ../secret_token_site:/secret_token_site
            - ./site.conf:/etc/nginx/conf.d/default.conf
